import { User } from "./types";

export const mockUsers: User[] = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2024-01-15",
    avatar: "JD",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2024-01-14",
    avatar: "JS",
  },
  {
    id: 3,
    name: "Mike Johnson",
    email: "mike.johnson@example.com",
    role: "Moderator",
    status: "Inactive",
    lastLogin: "2024-01-10",
    avatar: "MJ",
  },
  {
    id: 4,
    name: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2024-01-13",
    avatar: "SW",
  },
  {
    id: 5,
    name: "David Brown",
    email: "david.brown@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2024-01-12",
    avatar: "DB",
  },
  {
    id: 6,
    name: "Lisa Davis",
    email: "lisa.davis@example.com",
    role: "User",
    status: "Inactive",
    lastLogin: "2024-01-08",
    avatar: "LD",
  },
  {
    id: 7,
    name: "Tom Miller",
    email: "tom.miller@example.com",
    role: "Moderator",
    status: "Active",
    lastLogin: "2024-01-11",
    avatar: "TM",
  },
  {
    id: 8,
    name: "Emma Wilson",
    email: "emma.wilson@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2024-01-09",
    avatar: "EW",
  },
  {
    id: 9,
    name: "Alex Thompson",
    email: "alex.thompson@example.com",
    role: "User",
    status: "Inactive",
    lastLogin: "2024-01-07",
    avatar: "AT",
  },
  {
    id: 10,
    name: "Rachel Green",
    email: "rachel.green@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2024-01-06",
    avatar: "RG",
  },
  {
    id: 11,
    name: "Chris Lee",
    email: "chris.lee@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2024-01-05",
    avatar: "CL",
  },
  {
    id: 12,
    name: "Amanda White",
    email: "amanda.white@example.com",
    role: "Moderator",
    status: "Active",
    lastLogin: "2024-01-04",
    avatar: "AW",
  },
];
